config/routes.rb
Rails.application.routes.draw do

  resources :subjects
  resources :teachers
  resources :students
  resources :careers
  resources :scores
  get 'dashboard/index'

  resources :rols
  resources :users
  root 'sessions#new'
  get 'sessions/new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

end

app/models/student.rb
class Student
  include ActiveModel::Model

  attr_accessor :id, :code, :identification, :full_name, :date_of_birth, :email, :phone_number, :created_at, :updated_at, :url

  BASE_URL = 'https://api-university.herokuapp.com/students'
  HEADERS = {
      'token' => 'ef69a868-9912-43f6-9808-b86908ff64cb'
  }


  def self.path( request_path = '' )
    BASE_URL + request_path + '.json'
  end

  def persisted?
    self.id.present?
  end

  def attributes
    {
        student: {
            id: self.id,
            code: self.code,
            identification: self.identification,
            full_name: self.full_name,
            date_of_birth: self.date_of_birth,
            email: self.email,
            phone_number: self.phone_number,
        }
    }
  end

  def self.all
    response = HTTParty.get( path, headers: HEADERS )
    response.parsed_response.map do |student|
      new( student )
    end
  end

  def self.find( id )
    response = HTTParty.get( path("/#{id}"), headers: HEADERS )
    new( response.parsed_response )
  end

  def save
    response = HTTParty.post( self.class.path, query: attributes, headers: HEADERS )
  end

  def update
    response = HTTParty.put( self.class.path("/#{id}"), query: attributes, headers: HEADERS )
  end

  def destroy
    HTTParty.delete( self.class.path("/#{id}"), headers: HEADERS )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :logged_in?
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @student.date_of_birth = @student.date_of_birth.to_date
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update

    @student = Student.new( student_params )
    @student.id = params[:id]

    respond_to do |format|
      if @student.update
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      student = params[:student]
      date_of_birth = Date.new(student["date_of_birth(1i)"].to_i, student["date_of_birth(2i)"].to_i, student["date_of_birth(3i)"].to_i)
      params.require(:student).permit(:code, :identification, :full_name, :email, :phone_number).merge( date_of_birth: date_of_birth.to_s  )
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.text_field :identification %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', student_path(@student.id) %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Code</th>
      <th>Identification</th>
      <th>Full name</th>
      <th>Date of birth</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.code %></td>
        <td><%= student.identification %></td>
        <td><%= student.full_name %></td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.email %></td>
        <td><%= student.phone_number %></td>
        <td><%= link_to 'Show', student_path(student.id) %></td>
        <td><%= link_to 'Edit', edit_student_path(student.id) %></td>
        <td><%= link_to 'Destroy', student_path(student.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @student.code %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @student.identification %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @student.phone_number %>
</p>

<%= link_to 'Edit', edit_student_path(@student.id) %> |
<%= link_to 'Back', students_path %>