config/routes.rb
Rails.application.routes.draw do

  resources :subjects
  resources :teachers
  resources :students
  resources :careers
  resources :scores
  get 'dashboard/index'

  resources :rols
  resources :users
  root 'sessions#new'
  get 'sessions/new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

end

app/models/subject.rb
class Subject
  include ActiveModel::Model

  attr_accessor :id, :code, :name, :credits, :cycle, :room, :description, :hours, :created_at, :updated_at, :url

  BASE_URL = 'https://api-university.herokuapp.com/subjects'
  HEADERS = {
      'token' => 'ef69a868-9912-43f6-9808-b86908ff64cb'
  }


  def self.path( request_path = '' )
    BASE_URL + request_path + '.json'
  end

  def persisted?
    self.id.present?
  end

  def attributes
    {
        subject: {
            id: self.id,
            code: self.code,
            name: self.name,
            credits: self.credits,
            cycle: self.cycle,
            room: self.room,
            description: self.description,
            hours: self.hours,
        }
    }
  end

  def self.all
    response = HTTParty.get( path, headers: HEADERS )
    response.parsed_response.map do |subject|
      new( subject )
    end
  end

  def self.find( id )
    response = HTTParty.get( path("/#{id}"), headers: HEADERS )
    new( response.parsed_response )
  end

  def save
    HTTParty.post( self.class.path, query: attributes, headers: HEADERS )
  end

  def update
    HTTParty.put( self.class.path("/#{id}"), query: attributes, headers: HEADERS )
  end

  def destroy
    HTTParty.delete( self.class.path("/#{id}"), headers: HEADERS )
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :logged_in?
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update

    @subject = Subject.new( subject_params )
    @subject.id = params[:id]

    respond_to do |format|
      if @subject.update
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:code, :name, :credits, :cycle, :room, :description, :hours)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credits %><br>
    <%= f.number_field :credits %>
  </div>
  <div class="field">
    <%= f.label :cycle %><br>
    <%= f.text_field :cycle %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.number_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>


<%= link_to 'Show', subjects_path(@subject.id) %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Credits</th>
      <th>Cycle</th>
      <th>Room</th>
      <th>Description</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.code %></td>
        <td><%= subject.name %></td>
        <td><%= subject.credits %></td>
        <td><%= subject.cycle %></td>
        <td><%= subject.room %></td>
        <td><%= subject.description %></td>
        <td><%= subject.hours %></td>
        <td><%= link_to 'Show', subject_path(subject.id) %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject.id) %></td>
        <td><%= link_to 'Destroy', subject_path(subject.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @subject.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @subject.credits %>
</p>

<p>
  <strong>Cycle:</strong>
  <%= @subject.cycle %>
</p>

<p>
  <strong>Room:</strong>
  <%= @subject.room %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @subject.hours %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject.id) %> |
<%= link_to 'Back', subjects_path %>