config/routes.rb
Rails.application.routes.draw do

  resources :subjects
  resources :teachers
  resources :students
  resources :careers
  resources :scores
  get 'dashboard/index'

  resources :rols
  resources :users
  root 'sessions#new'
  get 'sessions/new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

end

app/models/teacher.rb
class Teacher
  include ActiveModel::Model

  attr_accessor :id, :code, :identification, :full_name, :date_of_birth, :email, :office, :phone_number, :amount_hour, :created_at, :updated_at, :url
  validates :code, presence: true
  validates :identification, presence: true
  validates :full_name, presence: true
  validates :user_name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  BASE_URL = 'https://api-university.herokuapp.com/teachers'
  HEADERS = {
      'token' => 'ef69a868-9912-43f6-9808-b86908ff64cb'
  }


  def self.path( request_path = '' )
    BASE_URL + request_path + '.json'
  end

  def persisted?
    self.id.present?
  end

  def attributes
    {
        teacher: {
        id: self.id,
        code: self.code,
        identification: self.identification,
        full_name: self.full_name,
        date_of_birth: self.date_of_birth,
        email: self.email,
        office: self.office,
        phone_number: self.phone_number,
        amount_hour: self.amount_hour
      }
    }
  end

  def self.all
    response = HTTParty.get( path, headers: HEADERS )
    response.parsed_response.map do |teacher|
      new( teacher )
    end
  end

  def self.find( id )
    response = HTTParty.get( path("/#{id}"), headers: HEADERS )
    new( response.parsed_response )
  end

  def save
    response = HTTParty.post( self.class.path, query: attributes, headers: HEADERS )
  end

  def update
    response = HTTParty.put( self.class.path("/#{id}"), query: attributes, headers: HEADERS )
  end

  def destroy
    HTTParty.delete( self.class.path("/#{id}"), headers: HEADERS )
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in?
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
    @teacher.date_of_birth = @teacher.date_of_birth.to_date
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update

    @teacher = Teacher.new( teacher_params )
    @teacher.id = params[:id]

    respond_to do |format|
      if @teacher.update
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      teacher = params[:teacher]
      date_of_birth = Date.new(teacher["date_of_birth(1i)"].to_i, teacher["date_of_birth(2i)"].to_i, teacher["date_of_birth(3i)"].to_i)
      params.require(:teacher).permit(:code, :identification, :full_name, :email, :office, :phone_number, :amount_hour).merge( date_of_birth: date_of_birth.to_s  )
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.text_field :identification %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth, :start_year => Date.current.year, :end_year => 1920 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :office %><br>
    <%= f.number_field :office %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :amount_hour %><br>
    <%= f.text_field :amount_hour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>


<%= link_to 'Show', teacher_path(@teacher.id) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Identification</th>
      <th>Full name</th>
      <th>Date of birth</th>
      <th>Email</th>
      <th>Office</th>
      <th>Phone number</th>
      <th>Amount hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.code %></td>
        <td><%= teacher.identification %></td>
        <td><%= teacher.full_name %></td>
        <td><%= teacher.date_of_birth %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.office %></td>
        <td><%= teacher.phone_number %></td>
        <td><%= teacher.amount_hour %></td>
        <td><%= link_to 'Show', teacher_path(teacher.id) %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher.id) %></td>
        <td><%= link_to 'Destroy', teacher_path(teacher.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @teacher.code %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @teacher.identification %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @teacher.full_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @teacher.date_of_birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Office:</strong>
  <%= @teacher.office %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @teacher.phone_number %>
</p>

<p>
  <strong>Amount hour:</strong>
  <%= @teacher.amount_hour %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher.id) %> |
<%= link_to 'Back', teachers_path %>